import express, { IRouter } from "express";
import * as authController from "../controllers/auth.controller";
const router: IRouter = express.Router();
router.post("/register", authController.registerUser);
router.post("/login", authController.loginUser);
router.post("/logout", authController.logoutUser);
router.post("/refresh", authController.refreshToken);
router.get("/verify", authController.verifyToken);
router.get("/google/url", authController.getGoogleAuthUrl);
router.get("/google/callback", authController.handleGoogleCallback);
router.get("/user/:id", authController.getUserById);
router.post("/password/request-reset", authController.requestPasswordReset);
router.get("/password/consume", authController.consumeResetToken);
router.post("/password/reset-with-cookie", authController.resetPasswordWithCookie);
export default router;
