import { Router } from "express";
import * as dreamController from "../controllers/dream.controller";
import authenticate from "../middlewares/authenticate";
import authenticateLite from "../middlewares/authenticateLite";
const router = Router();
router.post("/interpret", authenticate, dreamController.interpretDream);
router.post("/", authenticate, dreamController.createDream);
router.get("/", authenticateLite, dreamController.getAllDreams);
router.get("/stats", authenticateLite, dreamController.getDreamStats);
router.get("/:id([0-9a-fA-F]{24})", authenticateLite, dreamController.getDreamById);
router.put("/:id([0-9a-fA-F]{24})", authenticate, dreamController.updateDream);
router.delete("/:id([0-9a-fA-F]{24})", authenticate, dreamController.deleteDream);
export default router;
